import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
import Background from '@/components/background'
import Header from '@/components/header/header'


const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  

  return (
    <html lang="pt-br">
      <body className={`${inter.className} h-full`}>
        <Background/>
        <Header />
        
        {children}</body>
    </html>
  )
}
