import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Background from "@/components/background";
import { Header } from "@/components/comp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "What Movie",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br ">
      <body className={`${inter.className} bg-[#ECF0F3] dark:bg-[#0a0a0a] `}>
        <Background />
        <Header />
        {children}

      </body>
    </html>
  );
}
