import "./globals.css";
import type { Metadata , Viewport } from "next";
import { Barlow } from "next/font/google";
// import Background from "@/components/background";
import { Header } from "@/components/comps";

const barlow = Barlow({weight: ['400', '500', '600'], subsets: ['latin']})

export const metadata: Metadata = {
  title: "What Movie",
  description: "Generated by create next app",
};

export const viewport: Viewport = {
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#e4e6e6fe' },
    // { media: '(prefers-color-scheme: dark)', color: '#0A0A0A' },
    { media: '(prefers-color-scheme: dark)', color: '#e4e6e6fe' },
   
  ],
}


export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-br" className={barlow.className}>
      <body className="bg-Background overflow-x-hidden min-h-dvh ">
        {/* <Background /> */}
        <Header />
        {children}

      </body>
    </html>
  );
}
